# Generated by Django 2.2.4 on 2019-08-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'epoch',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prevision',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warner.Epoch')),
                ('prevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warner.Prevision')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='epoch',
            name='prevision_set',
            field=models.ManyToManyField(to='warner.Prevision'),
        ),
    ]
