# Generated by Django 2.2.4 on 2019-08-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warner', '0002_transaction_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prevision',
            new_name='Forecast',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='prevision',
            new_name='forecast',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='prevision_set',
        ),
        migrations.AddField(
            model_name='epoch',
            name='forecast_set',
            field=models.ManyToManyField(blank=True, to='warner.Forecast'),
        ),
        migrations.AlterModelTable(
            name='forecast',
            table='forecast',
        ),
    ]
