# Generated by Django 2.2.4 on 2019-08-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warner', '0003_auto_20190824_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='forecast',
            name='is_inevitable',
            field=models.BooleanField(default=False),
        ),
    ]
