# Generated by Django 2.2.4 on 2019-08-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warner', '0004_auto_20190824_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='is_useful',
            field=models.BooleanField(default=False),
        ),
    ]
