# Generated by Django 2.2.4 on 2019-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warner', '0005_epoch_is_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
