# Generated by Django 2.2.4 on 2019-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warner', '0006_forecast_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Epoch',
            new_name='Episode',
        ),
    ]
